In [94]:
import os
import glob
import pandas as pd

corpora = ['mpdd','cejc']
situtation_list = ['apology','request','thanksgiving', 'negative']
# method = {'original':'pre-translated','translated':'machine translated','rewrited':'human translated'}
sentence_type = {'query':'query'}
dataset_part = ['train','val','test']
for_table = pd.DataFrame()
for corpus in corpora:
    for situation in situtation_list:
        for sen_type,sen_type_name in sentence_type.items():
#             for m_type, m_type_name in method.items():
            for d_part in dataset_part:
                dir_name = f'data/{corpus}/{situation}/'
                path = dir_name + f'relation_pair_{d_part}'
                tmp = pd.read_csv(path, names=["query","res"])
                count = len(tmp)
                tmp = tmp['query'].value_counts()
                tmp = pd.DataFrame(tmp).T
                tmp['corpus'] = corpus
                tmp['situation'] = situation
                tmp['d_part'] = d_part
                tmp['count'] = count
                for_table = pd.concat([for_table,tmp])
display(for_table.columns)
for_table = for_table.set_index(['corpus','situation','d_part','count'])
for_table = for_table[[
                     'parent','parent-in-law','grandparent','other superior',
                     'spouse','brothers and sisters','other peer',
                     'child','son/daughter-in-law','grandchild','other inferior',
                     'teacher','classmate','student',
                     'boss','colleague','partner','subordinate',
                     'couple','friend','enemy','consignor','consignee','stranger','unknown']]
for_table=for_table.fillna(0)
for_table.to_csv('for_thesis/num_relation.csv')
for_table

Index(['friend', 'stranger', 'spouse', 'subordinate', 'child', 'couple',
       'colleague', 'parent', 'other peer', 'consignee',
       'brothers and sisters', 'classmate', 'student', 'enemy',
       'other inferior', 'boss', 'partner', 'other superior', 'consignor',
       'corpus', 'situation', 'd_part', 'count', 'teacher', 'grandchild',
       'parent-in-law', 'unknown', 'son/daughter-in-law', 'grandparent',
       'son/daughter-in-law''],
      dtype='object')

                                  parent  parent-in-law  grandparent  \
corpus situation    d_part count
mpdd   apology      train  107       4.0            0.0          0.0
                    val    13        0.0            0.0          0.0
                    test   14        0.0            0.0          0.0
       request      train  347       6.0            2.0          0.0
                    val    43        1.0            0.0          0.0
                    test   44        1.0            1.0          1.0
       thanksgiving train  176       2.0            1.0          0.0
                    val    22        0.0            0.0          0.0
                    test   22        2.0            0.0          0.0
       negative     train  16948  1177.0          111.0         41.0
                    val    2119    141.0           10.0          3.0
                    test   2119    156.0           11.0          4.0
cejc   apology      train  335      30.0            8.0          2.0
                    val    42        3.0            0.0          1.0
                    test   42        4.0            1.0          0.0
       request      train  69        1.0            1.0          0.0
                    val    9         1.0            1.0          0.0
                    test   9         0.0            0.0          0.0
       thanksgiving train  283      16.0            5.0          3.0
                    val    35        4.0            2.0          1.0
                    test   36        2.0            0.0          0.0
       negative     train  72384  5978.0         1385.0        365.0
                    val    9048    650.0          179.0         42.0
                    test   9048    828.0          177.0         50.0

                                  other superior  spouse  \
corpus situation    d_part count
mpdd   apology      train  107               1.0     8.0
                    val    13                0.0     1.0
                    test   14                2.0     1.0
       request      train  347               3.0    27.0
                    val    43                1.0     2.0
                    test   44                0.0     3.0
       thanksgiving train  176               0.0     6.0
                    val    22                0.0     1.0
                    test   22                1.0     1.0
       negative     train  16948           192.0  1688.0
                    val    2119             27.0   196.0
                    test   2119             23.0   210.0
cejc   apology      train  335               2.0    19.0
                    val    42                1.0     4.0
                    test   42                0.0     0.0
       request      train  69                0.0     5.0
                    val    9                 0.0     1.0
                    test   9                 0.0     1.0
       thanksgiving train  283               0.0    20.0
                    val    35                0.0     1.0
                    test   36                0.0     3.0
       negative     train  72384           127.0  7501.0
                    val    9048             18.0   937.0
                    test   9048              9.0   945.0

                                  brothers and sisters  other peer   child  \
corpus situation    d_part count
mpdd   apology      train  107                     3.0         4.0     7.0
                    val    13                      1.0         0.0     1.0
                    test   14                      1.0         0.0     1.0
       request      train  347                    10.0         4.0    12.0
                    val    43                      1.0         0.0     2.0
                    test   44                      1.0         1.0     0.0
       thanksgiving train  176                     8.0         4.0     9.0
                    val    22                      0.0         0.0     1.0
                    test   22                      0.0         1.0     0.0
       negative     train  16948                1007.0       380.0  1250.0
                    val    2119                  130.0        41.0   167.0
                    test   2119                  126.0        46.0   148.0
cejc   apology      train  335                     4.0         4.0    14.0
                    val    42                      0.0         1.0     2.0
                    test   42                      1.0         1.0     3.0
       request      train  69                      0.0         0.0     5.0
                    val    9                       0.0         0.0     0.0
                    test   9                       0.0         0.0     1.0
       thanksgiving train  283                     6.0         3.0    13.0
                    val    35                      0.0         0.0     1.0
                    test   36                      1.0         0.0     2.0
       negative     train  72384                2831.0      1206.0  6068.0
                    val    9048                  354.0       143.0   852.0
                    test   9048                  344.0       145.0   698.0

                                  son/daughter-in-law  grandchild  ...  \
corpus situation    d_part count                                   ...
mpdd   apology      train  107                    0.0         0.0  ...
                    val    13                     0.0         0.0  ...
                    test   14                     0.0         0.0  ...
       request      train  347                    1.0         3.0  ...
                    val    43                     0.0         0.0  ...
                    test   44                     0.0         0.0  ...
       thanksgiving train  176                    1.0         2.0  ...
                    val    22                     0.0         0.0  ...
                    test   22                     0.0         0.0  ...
       negative     train  16948                 84.0        64.0  ...
                    val    2119                  17.0         9.0  ...
                    test   2119                  11.0         9.0  ...
cejc   apology      train  335                    3.0         2.0  ...
                    val    42                     0.0         0.0  ...
                    test   42                     1.0         0.0  ...
       request      train  69                     0.0         0.0  ...
                    val    9                      0.0         0.0  ...
                    test   9                      0.0         0.0  ...
       thanksgiving train  283                    2.0         2.0  ...
                    val    35                     2.0         0.0  ...
                    test   36                     0.0         0.0  ...
       negative     train  72384               1250.0       338.0  ...
                    val    9048                 152.0        48.0  ...
                    test   9048                 149.0        35.0  ...

                                  colleague  partner  subordinate  couple  \
corpus situation    d_part count
mpdd   apology      train  107          6.0      1.0          8.0     6.0
                    val    13           1.0      0.0          0.0     4.0
                    test   14           1.0      0.0          0.0     2.0
       request      train  347         28.0      4.0         28.0     8.0
                    val    43           3.0      1.0          5.0     0.0
                    test   44           3.0      0.0          5.0     2.0
       thanksgiving train  176         12.0      1.0          8.0     3.0
                    val    22           1.0      1.0          1.0     0.0
                    test   22           3.0      0.0          2.0     1.0
       negative     train  16948     1234.0    193.0        970.0  1131.0
                    val    2119       164.0     23.0        129.0   139.0
                    test   2119       142.0     27.0        120.0   143.0
cejc   apology      train  335         18.0     17.0          2.0     1.0
                    val    42           4.0      1.0          0.0     0.0
                    test   42           1.0      3.0          0.0     0.0
       request      train  69           0.0     15.0          0.0     0.0
                    val    9            0.0      2.0          0.0     0.0
                    test   9            0.0      2.0          0.0     0.0
       thanksgiving train  283         19.0     14.0          2.0     0.0
                    val    35           2.0      2.0          0.0     0.0
                    test   36           4.0      3.0          0.0     0.0
       negative     train  72384     3381.0   2848.0        140.0   463.0
                    val    9048       402.0    355.0         15.0    59.0
                    test   9048       416.0    357.0         12.0    52.0

                                  friend  enemy  consignor  consignee  \
corpus situation    d_part count
mpdd   apology      train  107        36    2.0        1.0        4.0
                    val    13          4    0.0        0.0        0.0
                    test   14          4    0.0        1.0        0.0
       request      train  347        69    7.0        9.0       17.0
                    val    43          9    1.0        1.0        2.0
                    test   44         14    1.0        0.0        3.0
       thanksgiving train  176        76    2.0       17.0        0.0
                    val    22          7    1.0        3.0        0.0
                    test   22          6    1.0        2.0        0.0
       negative     train  16948    4313  514.0      339.0      326.0
                    val    2119      548   68.0       41.0       35.0
                    test   2119      547   65.0       54.0       35.0
cejc   apology      train  335       137    0.0       25.0       22.0
                    val    42         15    0.0        3.0        4.0
                    test   42         16    0.0        4.0        5.0
       request      train  69         19    0.0        3.0       10.0
                    val    9           2    0.0        0.0        1.0
                    test   9           4    0.0        0.0        0.0
       thanksgiving train  283       127    0.0       16.0       19.0
                    val    35         15    0.0        2.0        3.0
                    test   36         14    0.0        2.0        4.0
       negative     train  72384   30622    0.0     1526.0     1498.0
                    val    9048     3829    0.0      186.0      211.0
                    test   9048     3844    0.0      194.0      187.0

                                  stranger  unknown
corpus situation    d_part count
mpdd   apology      train  107         8.0      0.0
                    val    13          0.0      0.0
                    test   14          1.0      0.0
       request      train  347        15.0      2.0
                    val    43          5.0      0.0
                    test   44          0.0      0.0
       thanksgiving train  176         6.0      0.0
                    val    22          0.0      0.0
                    test   22          0.0      0.0
       negative     train  16948     523.0     10.0
                    val    2119       63.0      1.0
                    test   2119       58.0      1.0
cejc   apology      train  335         0.0      0.0
                    val    42          0.0      0.0
                    test   42          0.0      1.0
       request      train  69          0.0      0.0
                    val    9           0.0      0.0
                    test   9           0.0      0.0
       thanksgiving train  283         0.0      0.0
                    val    35          0.0      0.0
                    test   36          0.0      0.0
       negative     train  72384       0.0    227.0
                    val    9048        0.0     26.0
                    test   9048        0.0     32.0

[24 rows x 25 columns]

In [98]:
for_table_=for_table.reset_index().groupby(['corpus','situation']).sum()
for_table_=for_table_.reset_index().set_index(['corpus','situation'])
for_table_

                     count  parent  parent-in-law  grandparent  \
corpus situation
cejc   apology         419    37.0            9.0          3.0
       negative      90480  7456.0         1741.0        457.0
       request          87     2.0            2.0          0.0
       thanksgiving    354    22.0            7.0          4.0
mpdd   apology         134     4.0            0.0          0.0
       negative      21186  1474.0          132.0         48.0
       request         434     8.0            3.0          1.0
       thanksgiving    220     4.0            1.0          0.0

                     other superior  spouse  brothers and sisters  other peer  \
corpus situation
cejc   apology                  3.0    23.0                   5.0         6.0
       negative               154.0  9383.0                3529.0      1494.0
       request                  0.0     7.0                   0.0         0.0
       thanksgiving             0.0    24.0                   7.0         3.0
mpdd   apology                  3.0    10.0                   5.0         4.0
       negative               242.0  2094.0                1263.0       467.0
       request                  4.0    32.0                  12.0         5.0
       thanksgiving             1.0     8.0                   8.0         5.0

                      child  son/daughter-in-law  ...  colleague  partner  \
corpus situation                                  ...
cejc   apology         19.0                  4.0  ...       23.0     21.0
       negative      7618.0               1551.0  ...     4199.0   3560.0
       request          6.0                  0.0  ...        0.0     19.0
       thanksgiving    16.0                  4.0  ...       25.0     19.0
mpdd   apology          9.0                  0.0  ...        8.0      1.0
       negative      1565.0                112.0  ...     1540.0    243.0
       request         14.0                  1.0  ...       34.0      5.0
       thanksgiving    10.0                  1.0  ...       16.0      2.0

                     subordinate  couple  friend  enemy  consignor  consignee  \
corpus situation
cejc   apology               2.0     1.0     168    0.0       32.0       31.0
       negative            167.0   574.0   38295    0.0     1906.0     1896.0
       request               0.0     0.0      25    0.0        3.0       11.0
       thanksgiving          2.0     0.0     156    0.0       20.0       26.0
mpdd   apology               8.0    12.0      44    2.0        2.0        4.0
       negative           1219.0  1413.0    5408  647.0      434.0      396.0
       request              38.0    10.0      92    9.0       10.0       22.0
       thanksgiving         11.0     4.0      89    4.0       22.0        0.0

                     stranger  unknown
corpus situation
cejc   apology            0.0      1.0
       negative           0.0    285.0
       request            0.0      0.0
       thanksgiving       0.0      0.0
mpdd   apology            9.0      0.0
       negative         644.0     12.0
       request           20.0      2.0
       thanksgiving       6.0      0.0

[8 rows x 26 columns]

In [99]:
print(for_table_.columns.to_list())
for col in for_table_.columns.to_list():
    if col == 'count': 
        continue
    for_table_[col]=for_table_[col]/for_table_['count']

for_table_=for_table_[[
                     'parent','parent-in-law','grandparent','other superior',
                     'spouse','brothers and sisters','other peer',
                     'child','son/daughter-in-law','grandchild','other inferior',
                     'teacher','classmate','student',
                     'boss','colleague','partner','subordinate',
                     'couple','friend','enemy','consignor','consignee','stranger','unknown']]

for_table_.to_csv('for_thesis/rate_relation.csv')
for_table_

['count', 'parent', 'parent-in-law', 'grandparent', 'other superior', 'spouse', 'brothers and sisters', 'other peer', 'child', 'son/daughter-in-law', 'grandchild', 'other inferior', 'teacher', 'classmate', 'student', 'boss', 'colleague', 'partner', 'subordinate', 'couple', 'friend', 'enemy', 'consignor', 'consignee', 'stranger', 'unknown']

                       parent  parent-in-law  grandparent  other superior  \
corpus situation
cejc   apology       0.088305       0.021480     0.007160        0.007160
       negative      0.082405       0.019242     0.005051        0.001702
       request       0.022989       0.022989     0.000000        0.000000
       thanksgiving  0.062147       0.019774     0.011299        0.000000
mpdd   apology       0.029851       0.000000     0.000000        0.022388
       negative      0.069574       0.006231     0.002266        0.011423
       request       0.018433       0.006912     0.002304        0.009217
       thanksgiving  0.018182       0.004545     0.000000        0.004545

                       spouse  brothers and sisters  other peer     child  \
corpus situation
cejc   apology       0.054893              0.011933    0.014320  0.045346
       negative      0.103702              0.039003    0.016512  0.084195
       request       0.080460              0.000000    0.000000  0.068966
       thanksgiving  0.067797              0.019774    0.008475  0.045198
mpdd   apology       0.074627              0.037313    0.029851  0.067164
       negative      0.098839              0.059615    0.022043  0.073870
       request       0.073733              0.027650    0.011521  0.032258
       thanksgiving  0.036364              0.036364    0.022727  0.045455

                     son/daughter-in-law  grandchild  ...  colleague  \
corpus situation                                      ...
cejc   apology                  0.009547    0.004773  ...   0.054893
       negative                 0.017142    0.004653  ...   0.046408
       request                  0.000000    0.000000  ...   0.000000
       thanksgiving             0.011299    0.005650  ...   0.070621
mpdd   apology                  0.000000    0.000000  ...   0.059701
       negative                 0.005287    0.003870  ...   0.072690
       request                  0.002304    0.006912  ...   0.078341
       thanksgiving             0.004545    0.009091  ...   0.072727

                      partner  subordinate    couple    friend     enemy  \
corpus situation
cejc   apology       0.050119     0.004773  0.002387  0.400955  0.000000
       negative      0.039346     0.001846  0.006344  0.423243  0.000000
       request       0.218391     0.000000  0.000000  0.287356  0.000000
       thanksgiving  0.053672     0.005650  0.000000  0.440678  0.000000
mpdd   apology       0.007463     0.059701  0.089552  0.328358  0.014925
       negative      0.011470     0.057538  0.066695  0.255263  0.030539
       request       0.011521     0.087558  0.023041  0.211982  0.020737
       thanksgiving  0.009091     0.050000  0.018182  0.404545  0.018182

                     consignor  consignee  stranger   unknown
corpus situation
cejc   apology        0.076372   0.073986  0.000000  0.002387
       negative       0.021065   0.020955  0.000000  0.003150
       request        0.034483   0.126437  0.000000  0.000000
       thanksgiving   0.056497   0.073446  0.000000  0.000000
mpdd   apology        0.014925   0.029851  0.067164  0.000000
       negative       0.020485   0.018692  0.030397  0.000566
       request        0.023041   0.050691  0.046083  0.004608
       thanksgiving   0.100000   0.000000  0.027273  0.000000

[8 rows x 25 columns]